import { readFile, readdir } from 'node:fs/promises';
import { join } from 'node:path';

/**
 * Project detection for `clarx init`.
 *
 * The rule here is: **derive or omit, never invent.**
 *
 * The previous version hardcoded `pnpm typecheck`, `pnpm test`, and `pnpm lint`
 * into every manifest it wrote, along with Next.js ignore globs — regardless of
 * what the project actually was. On a Cargo project with no package.json that is
 * a manifest asserting three commands that do not exist, generated by the tool
 * whose entire premise is telling agents what is true about a repository.
 *
 * A manifest that omits a field says "unknown". A manifest that guesses says
 * something false with the same confidence as everything else in the file, and
 * an agent has no way to tell the two apart.
 */

export type Ecosystem = 'node' | 'rust' | 'python' | 'go' | 'unknown';

export interface Detection {
  ecosystem: Ecosystem;
  /** Omitted entirely when nothing can be derived. */
  verificationCommands?: { typecheck?: string; test?: string; lint?: string };
  generated: string[];
}

async function exists(root: string, name: string): Promise<boolean> {
  try {
    await readFile(join(root, name), 'utf-8');
    return true;
  } catch {
    return false;
  }
}

export async function detectEcosystem(root: string): Promise<Ecosystem> {
  if (await exists(root, 'package.json')) return 'node';
  if (await exists(root, 'Cargo.toml')) return 'rust';
  if ((await exists(root, 'pyproject.toml')) || (await exists(root, 'setup.py'))) return 'python';
  if (await exists(root, 'go.mod')) return 'go';
  return 'unknown';
}

/** The package manager a Node project actually uses, from its own declarations. */
async function detectPackageManager(root: string): Promise<string> {
  try {
    const pkg = JSON.parse(await readFile(join(root, 'package.json'), 'utf-8')) as { packageManager?: string };
    const declared = pkg.packageManager?.split('@')[0];
    if (declared === 'pnpm' || declared === 'yarn' || declared === 'npm' || declared === 'bun') return declared;
  } catch {
    // fall through to lockfiles
  }
  if (await exists(root, 'pnpm-lock.yaml')) return 'pnpm';
  if (await exists(root, 'yarn.lock')) return 'yarn';
  if (await exists(root, 'bun.lockb')) return 'bun';
  return 'npm';
}

/**
 * Script names commonly used for each kind of check, in preference order. Only a
 * script the project actually declares is ever referenced.
 *
 * Check-style names are preferred over their bare equivalents where both exist.
 * These end up in `verificationCommands`, which an agent runs to confirm it has
 * not broken anything — and plenty of projects define `lint` as a mutating
 * fixer. gqloom's is `biome lint --write .`, which rewrites files; its
 * `check:lint` does not. Handing an agent the fixer as its verification step
 * invites edits nobody asked for.
 */
const SCRIPT_ALIASES: Record<'typecheck' | 'test' | 'lint', string[]> = {
  typecheck: ['typecheck', 'type-check', 'check:type', 'check-types', 'tsc'],
  test: ['test', 'tests'],
  lint: ['check:lint', 'lint:check', 'lint', 'eslint'],
};

async function nodeCommands(root: string): Promise<Detection['verificationCommands']> {
  let scripts: Record<string, string> = {};
  try {
    const pkg = JSON.parse(await readFile(join(root, 'package.json'), 'utf-8')) as { scripts?: Record<string, string> };
    scripts = pkg.scripts ?? {};
  } catch {
    return undefined;
  }

  const pm = await detectPackageManager(root);
  const commands: Record<string, string> = {};
  for (const [kind, aliases] of Object.entries(SCRIPT_ALIASES)) {
    const found = aliases.find(alias => typeof scripts[alias] === 'string');
    if (found) commands[kind] = `${pm} run ${found}`;
  }
  return Object.keys(commands).length > 0 ? commands : undefined;
}

/**
 * Non-Node ecosystems get commands only where the toolchain defines them
 * universally — `cargo test` works in any Cargo project by construction. That is
 * derivation, not a guess.
 */
function toolchainCommands(ecosystem: Ecosystem): Detection['verificationCommands'] {
  switch (ecosystem) {
    case 'rust':
      return { typecheck: 'cargo check', test: 'cargo test', lint: 'cargo clippy' };
    case 'go':
      return { typecheck: 'go build ./...', test: 'go test ./...', lint: 'go vet ./...' };
    // Python has no universal runner: pytest, unittest, tox, and nox are all
    // plausible and none is implied by pyproject.toml alone. Omitted rather
    // than guessed.
    default:
      return undefined;
  }
}

const GENERATED_BY_ECOSYSTEM: Record<Ecosystem, string[]> = {
  node: ['**/node_modules', '**/dist', '**/build', '**/coverage'],
  rust: ['target'],
  python: ['**/__pycache__', '**/.pytest_cache', '**/*.egg-info', '.venv'],
  go: ['bin'],
  unknown: [],
};

/** Directories that are only generated if the tool that generates them is in use. */
async function conditionalGenerated(root: string): Promise<string[]> {
  const found: string[] = [];
  try {
    const entries = await readdir(root, { withFileTypes: true });
    const names = new Set(entries.filter(e => e.isDirectory()).map(e => e.name));
    if (names.has('.next')) found.push('**/.next');
    if (names.has('.nuxt')) found.push('**/.nuxt');
    if (names.has('.source')) found.push('**/.source');
    if (names.has('.turbo')) found.push('**/.turbo');
    if (names.has('storybook-static')) found.push('storybook-static');
  } catch {
    // unreadable root — the caller reports this
  }
  return found;
}

export async function detect(root: string): Promise<Detection> {
  const ecosystem = await detectEcosystem(root);
  const verificationCommands =
    ecosystem === 'node' ? await nodeCommands(root) : toolchainCommands(ecosystem);

  return {
    ecosystem,
    ...(verificationCommands ? { verificationCommands } : {}),
    generated: [...new Set([...GENERATED_BY_ECOSYSTEM[ecosystem], ...(await conditionalGenerated(root))])],
  };
}
