import type { AnalysisResult, PillarName, RuleResult } from '@clarxai/engine';

const PILLAR_LABELS: Record<PillarName, string> = {
  discoverability: 'Discoverability',
  boundary_clarity: 'Boundary Clarity',
  context_efficiency: 'Context Efficiency',
  operational_guidance: 'Operational Guidance',
  edit_safety: 'Edit Safety',
};

const SEVERITY_BADGE: Record<string, string> = {
  hard_failure: '🔴 hard failure',
  warning: '🟡 warning',
  recommendation: '🔵 recommendation',
};

export function formatMarkdown(result: AnalysisResult, opts: { verbose?: boolean } = {}): string {
  const lines: string[] = [];
  const scoreEmoji = result.score >= 90 ? '🟢' : result.score >= 70 ? '🟡' : '🔴';

  lines.push(`## Clarx AI-First Score — ${scoreEmoji} ${result.score} / 100`);
  lines.push('');
  lines.push(`**Confidence:** ${result.confidence} &nbsp;|&nbsp; **Standard:** v${result.version} &nbsp;|&nbsp; **Scanned:** ${result.meta.filesScanned} files`);
  lines.push('');

  // Pillar table
  lines.push('### Pillar Scores');
  lines.push('');
  lines.push('| Pillar | Score |');
  lines.push('|--------|-------|');
  for (const [key, pillar] of Object.entries(result.pillars) as [PillarName, typeof result.pillars[PillarName]][]) {
    const flag = pillar.score < 70 ? ' ⚠️' : '';
    lines.push(`| ${PILLAR_LABELS[key]} | ${pillar.score} / 100${flag} |`);
  }
  lines.push('');

  const hardFailures = Object.values(result.rules).filter(r => !r.passed && r.severity === 'hard_failure');
  const warnings = Object.values(result.rules).filter(r => !r.passed && r.severity === 'warning');
  const recommendations = Object.values(result.rules).filter(r => !r.passed && r.severity === 'recommendation');

  if (hardFailures.length > 0) {
    lines.push('### 🔴 Hard Failures');
    lines.push('');
    lines.push('> These rules cap the overall score at 50 until resolved.');
    lines.push('');
    for (const rule of hardFailures) {
      lines.push(formatRuleBlock(rule));
    }
  }

  if (warnings.length > 0) {
    lines.push('### 🟡 Warnings');
    lines.push('');
    for (const rule of warnings) {
      lines.push(formatRuleBlock(rule));
    }
  }

  if (recommendations.length > 0) {
    lines.push('### 🔵 Recommendations');
    lines.push('');
    for (const rule of recommendations) {
      lines.push(formatRuleBlock(rule));
    }
  }

  if (opts.verbose) {
    const passing = Object.values(result.rules).filter(r => r.passed && r.scoreImpact > 0);
    if (passing.length > 0) {
      lines.push('### ✅ Passing');
      lines.push('');
      lines.push('| Rule | Message |');
      lines.push('|------|---------|');
      for (const rule of passing) {
        lines.push(`| \`${rule.id}\` | ${rule.message} |`);
      }
      lines.push('');
    }
  }

  if (hardFailures.length === 0 && warnings.length === 0 && recommendations.length === 0) {
    lines.push('### ✅ All checks passed');
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated by [clarx](https://github.com/clarxai/clarx) at ${result.meta.analyzedAt}*`);
  lines.push('');

  return lines.join('\n');
}

function formatRuleBlock(rule: RuleResult): string {
  const lines: string[] = [];
  lines.push(`**\`${rule.id}\`** — ${rule.message}`);
  if (rule.locations && rule.locations.length > 0) {
    lines.push('');
    for (const loc of rule.locations.slice(0, 10)) {
      lines.push(`- \`${loc.path}\`${loc.detail ? ` — ${loc.detail}` : ''}`);
    }
    if (rule.locations.length > 10) {
      lines.push(`- *…and ${rule.locations.length - 10} more*`);
    }
  }
  lines.push('');
  return lines.join('\n');
}
